# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('product', 'user')]),
        ),
    ]
