# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160520_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='name',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('IND', 'Indie'), ('MP', 'Multiplayer'), ('RPG', 'RPG'), ('RAC', 'Racing'), ('SIM', 'Simulation'), ('SPO', 'Sports'), ('STR', 'Strategy')], max_length=3),
        ),
    ]
