# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160520_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ('name',)},
        ),
    ]
