# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20160520_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='name',
            new_name='title',
        ),
    ]
