# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20160520_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
