# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20160521_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keys',
            field=models.CharField(blank=True, editable=False, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keys_size',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
