# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20160522_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keys',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keys_size',
            field=models.IntegerField(null=True),
        ),
    ]
