# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160522_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keys',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
    ]
