# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20160522_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keys_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
