# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20160522_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='users_rated',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
