# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20160522_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_rated',
        ),
    ]
