# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_users_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_rated',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
