# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_users_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
