# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20160524_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_keys',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
