# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20160525_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_location),
        ),
    ]
